package pipeline_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/heimdallm/daemon/internal/pipeline"
)

func fileDiff(path, body string) string {
	return fmt.Sprintf("diff --git a/%s b/%s\nindex 1..2 100644\n--- a/%s\n+++ b/%s\n@@ -1 +1 @@\n%s\n", path, path, path, path, body)
}

func TestFilterDiffNoise(t *testing.T) {
	diff := fileDiff("cmd/main.go", "+func main() {}") +
		fileDiff("go.sum", "+golang.org/x/sys v0.1 h1:abc") +
		fileDiff("web/package-lock.json", "+{}") +
		fileDiff("vendor/github.com/x/y.go", "+package y") +
		fileDiff("api/types.pb.go", "+// Code generated by protoc-gen-go. DO NOT EDIT.") +
		fileDiff("internal/gen/zz.go", "+// Code generated by stringer; DO NOT EDIT.") +
		"diff --git a/logo.png b/logo.png\nnew file mode 100644\nBinary files /dev/null and b/logo.png differ\n" +
		fileDiff("Cargo.lock", "+[[package]]") +
		fileDiff("docs/README.md", "+hello")

	got, omitted := pipeline.FilterDiffNoise(diff, pipeline.DefaultNoiseGlobs)
	for _, keep := range []string{"cmd/main.go", "docs/README.md"} {
		if !strings.Contains(got, "diff --git a/"+keep) {
			t.Errorf("filtered diff dropped %s:\n%s", keep, got)
		}
	}
	want := []string{"go.sum", "web/package-lock.json", "vendor/github.com/x/y.go", "api/types.pb.go", "internal/gen/zz.go", "logo.png", "Cargo.lock"}
	if strings.Join(omitted, ",") != strings.Join(want, ",") {
		t.Errorf("omitted = %v, want %v", omitted, want)
	}
	if !strings.HasPrefix(got, "[Not shown: 7 lockfile/generated/vendored/binary file(s): go.sum,") {
		t.Errorf("missing omitted note:\n%s", got)
	}
	if strings.Contains(got, "diff --git a/go.sum") {
		t.Error("go.sum section kept")
	}
}

func TestFilterDiffNoise_GlobSemantics(t *testing.T) {
	diff := fileDiff("a/b/c.lock", "+x") + fileDiff("top.txt", "+x") + fileDiff("keep/me.go", "+x")
	// A glob without a slash matches the file name at any depth; ? is one char.
	got, omitted := pipeline.FilterDiffNoise(diff, []string{"*.lock", "to?.txt", "  ", "[bad"})
	if strings.Join(omitted, ",") != "a/b/c.lock,top.txt" {
		t.Errorf("omitted = %v", omitted)
	}
	if !strings.Contains(got, "keep/me.go") {
		t.Errorf("kept file missing: %s", got)
	}
}

func TestFilterDiffNoise_KeepsDiffWhenEverythingIsNoiseOrNotGit(t *testing.T) {
	only := fileDiff("go.sum", "+x")
	if got, omitted := pipeline.FilterDiffNoise(only, pipeline.DefaultNoiseGlobs); got != only || omitted != nil {
		t.Errorf("an all-noise diff must be kept as-is, got %q %v", got, omitted)
	}
	plain := "+just some lines\n-without git headers\n"
	if got, omitted := pipeline.FilterDiffNoise(plain, pipeline.DefaultNoiseGlobs); got != plain || omitted != nil {
		t.Errorf("non-git diff changed: %q %v", got, omitted)
	}
	clean := fileDiff("a.go", "+x")
	if got, omitted := pipeline.FilterDiffNoise(clean, pipeline.DefaultNoiseGlobs); got != clean || omitted != nil {
		t.Errorf("clean diff changed: %q %v", got, omitted)
	}
}

func TestFilterDiffNoise_CapsOmittedNames(t *testing.T) {
	var b strings.Builder
	for i := 0; i < 25; i++ {
		b.WriteString(fileDiff(fmt.Sprintf("pkg%d/go.sum", i), "+x"))
	}
	b.WriteString(fileDiff("main.go", "+x"))
	got, omitted := pipeline.FilterDiffNoise(b.String(), pipeline.DefaultNoiseGlobs)
	if len(omitted) != 25 || !strings.Contains(got, "and 5 more]") {
		t.Errorf("omitted=%d note=%q", len(omitted), strings.SplitN(got, "\n", 2)[0])
	}
}
