package pipeline

import (
	"fmt"
	"path"
	"regexp"
	"strings"
	"sync"
)

// DefaultNoiseGlobs are the files the filter_noise measure drops from the diff
// when no glob list is configured: lockfiles, vendored and built output, and
// generated code. Mirrored by config.DefaultNoiseGlobs.
var DefaultNoiseGlobs = []string{
	"**/*.lock",
	"**/package-lock.json",
	"**/pnpm-lock.yaml",
	"**/go.sum",
	"**/vendor/**",
	"**/node_modules/**",
	"**/dist/**",
	"**/*.min.js",
	"**/*.min.css",
	"**/*.map",
	"**/*.pb.go",
	"**/*_generated.*",
	"**/*.g.dart",
	"**/*.snap",
}

// maxOmittedNames caps how many dropped paths the diff note lists by name.
const maxOmittedNames = 20

// diffFileHeader starts each file section of a unified git diff.
var diffFileHeader = regexp.MustCompile(`(?m)^diff --git `)

// generatedMarkers flag a file as generated when one appears in the first
// added lines of its diff (the conventional Go/protobuf/codegen headers).
var generatedMarkers = []string{"Code generated", "DO NOT EDIT", "@generated", "<auto-generated"}

// generatedProbeLines is how many added lines are checked for a marker.
const generatedProbeLines = 8

var globCache sync.Map // pattern -> *regexp.Regexp (nil for invalid)

// globRegexp translates a gitignore-style glob to an anchored regexp:
// "**/" spans any number of directories, "**" anything, "*" and "?" stay
// within one path segment. Invalid patterns return nil and never match.
func globRegexp(pattern string) *regexp.Regexp {
	if v, ok := globCache.Load(pattern); ok {
		re, _ := v.(*regexp.Regexp)
		return re
	}
	var b strings.Builder
	b.WriteString("^")
	for i := 0; i < len(pattern); i++ {
		c := pattern[i]
		switch {
		case c == '*' && i+1 < len(pattern) && pattern[i+1] == '*':
			i++
			if i+1 < len(pattern) && pattern[i+1] == '/' {
				i++
				b.WriteString("(?:.*/)?")
			} else {
				b.WriteString(".*")
			}
		case c == '*':
			b.WriteString("[^/]*")
		case c == '?':
			b.WriteString("[^/]")
		default:
			b.WriteString(regexp.QuoteMeta(string(c)))
		}
	}
	b.WriteString("$")
	re, err := regexp.Compile(b.String())
	if err != nil {
		re = nil
	}
	globCache.Store(pattern, re)
	return re
}

// matchesNoiseGlob reports whether file matches any glob. A glob without a
// slash matches the file name at any depth, like .gitignore.
func matchesNoiseGlob(file string, globs []string) bool {
	for _, g := range globs {
		g = strings.TrimSpace(g)
		if g == "" {
			continue
		}
		target := file
		if !strings.Contains(g, "/") {
			target = path.Base(file)
		}
		if re := globRegexp(g); re != nil && re.MatchString(target) {
			return true
		}
	}
	return false
}

// diffSectionPath extracts the post-image path ("b/...") of a file section,
// falling back to the pre-image for deletions.
func diffSectionPath(section string) string {
	firstLine, _, _ := strings.Cut(section, "\n")
	// "a/old b/new"; paths with spaces are rare enough that splitting on the
	// last " b/" is the pragmatic choice git's own porcelain makes.
	if i := strings.LastIndex(firstLine, " b/"); i >= 0 {
		return firstLine[i+3:]
	}
	fields := strings.Fields(firstLine)
	if len(fields) == 0 {
		return ""
	}
	return strings.TrimPrefix(fields[0], "a/")
}

func isBinarySection(section string) bool {
	return strings.Contains(section, "\nBinary files ") || strings.Contains(section, "\nGIT binary patch")
}

func isGeneratedSection(section string) bool {
	probed := 0
	for _, line := range strings.Split(section, "\n") {
		if !strings.HasPrefix(line, "+") || strings.HasPrefix(line, "+++") {
			continue
		}
		for _, m := range generatedMarkers {
			if strings.Contains(line, m) {
				return true
			}
		}
		probed++
		if probed >= generatedProbeLines {
			return false
		}
	}
	return false
}

// FilterDiffNoise drops lockfiles, vendored/built output, binaries and
// generated files from a unified git diff (the filter_noise measure), so the
// diff budget is spent on code a reviewer would actually read. It returns the
// filtered diff and the dropped paths. A diff that is not in git's format is
// returned unchanged. When every file would be dropped the original is kept:
// a review with an empty diff helps nobody.
func FilterDiffNoise(diff string, globs []string) (string, []string) {
	locs := diffFileHeader.FindAllStringIndex(diff, -1)
	if len(locs) == 0 {
		return diff, nil
	}
	var kept strings.Builder
	kept.WriteString(diff[:locs[0][0]])
	var omitted []string
	keptAny := false
	for i, loc := range locs {
		end := len(diff)
		if i+1 < len(locs) {
			end = locs[i+1][0]
		}
		section := diff[loc[0]:end]
		body := section[len("diff --git "):]
		file := diffSectionPath(body)
		if matchesNoiseGlob(file, globs) || isBinarySection(section) || isGeneratedSection(section) {
			omitted = append(omitted, file)
			continue
		}
		kept.WriteString(section)
		keptAny = true
	}
	if !keptAny {
		return diff, nil
	}
	if len(omitted) == 0 {
		return diff, nil
	}
	return omittedNote(omitted) + kept.String(), omitted
}

// omittedNote tells the model which files exist in the PR but are not shown,
// so it does not flag them as missing.
func omittedNote(omitted []string) string {
	names := omitted
	extra := ""
	if len(names) > maxOmittedNames {
		extra = fmt.Sprintf(" and %d more", len(names)-maxOmittedNames)
		names = names[:maxOmittedNames]
	}
	return fmt.Sprintf("[Not shown: %d lockfile/generated/vendored/binary file(s): %s%s]\n",
		len(omitted), strings.Join(names, ", "), extra)
}
